[project]
name = "robotstxt-change-monitor"
version = "1.0.0"
description = "Monitor and report changes across one or more robots.txt files."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "requests==2.32.*",
]
